version: '3.7'
services:

  web:
    container_name: 4auto
    build:
      context: ./4auto
      args:
        - RUN_DB_MIGRATIONS_ARG=yes
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./4auto:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./.dev.env    
    depends_on:
      - db
  db:
    container_name: postgre
    image: postgres:12.0
    env_file:
      - ./.dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:  
      - '5432:5432'
networks:
  postgres:
    driver: bridge
 
volumes:
  postgres_data: