version: '3.7'

services:
  web:
    build:
      context: ./4auto
      dockerfile: Dockerfile.prod
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - 8000
    env_file:
      - ./.prod.env
    depends_on:
      - db
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.prod.db.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 1337:80
    depends_on:
      - web    

volumes:
  postgres_data:
  static_volume:
  media_volume: