version: '3.7'

services:
  web:
    image: timsson/4auto:latest
    container_name: 4auto_web
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.prod.env
    depends_on:
      - db
  db:
    image: postgres:12.0
    container_name: 4auto_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.prod.db.env
  nginx:
    build: ./nginx
    container_name: 4auto_ngnix
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web    
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  postgres_data:
  static_volume:
  media_volume: